//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROProtocol.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PROProtocol.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    &quot;None&quot;,
        ///    &quot;Stench&quot;,
        ///    &quot;Drizzle&quot;,
        ///    &quot;Speed Boost&quot;,
        ///    &quot;Battle Armor&quot;,
        ///    &quot;Sturdy&quot;,
        ///    &quot;Damp&quot;,
        ///    &quot;Limber&quot;,
        ///    &quot;Sand Veil&quot;,
        ///    &quot;Static&quot;,
        ///    &quot;Volt Absorb&quot;,
        ///    &quot;Water Absorb&quot;,
        ///    &quot;Oblivious&quot;,
        ///    &quot;Cloud Nine&quot;,
        ///    &quot;Compound Eyes&quot;,
        ///    &quot;Insomnia&quot;,
        ///    &quot;Color Change&quot;,
        ///    &quot;Immunity&quot;,
        ///    &quot;Flash Fire&quot;,
        ///    &quot;Shield Dust&quot;,
        ///    &quot;Own Tempo&quot;,
        ///    &quot;Suction Cups&quot;,
        ///    &quot;Intimidate&quot;,
        ///    &quot;Shadow Tag&quot;,
        ///    &quot;Rough Skin&quot;,
        ///    &quot;Wonder Guard&quot;,
        ///    &quot;Levitate&quot;,
        ///    &quot;Effect Spore&quot;,
        ///    &quot;Synchronize&quot;,
        ///    &quot;Clea [rest of string was truncated]&quot;;.
        /// </summary>
        public static string abilities {
            get {
                return ResourceManager.GetString("abilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;1&quot;: {
        ///        &quot;Accuracy&quot;: 100,
        ///        &quot;DamageType&quot;: 1,
        ///        &quot;Name&quot;: &quot;Absorb&quot;,
        ///        &quot;Power&quot;: 20,
        ///        &quot;Status&quot;: false,
        ///        &quot;Type&quot;: &quot;grass&quot;
        ///    },
        ///    &quot;2&quot;: {
        ///        &quot;Accuracy&quot;: 100,
        ///        &quot;DamageType&quot;: 1,
        ///        &quot;Name&quot;: &quot;Acid&quot;,
        ///        &quot;Power&quot;: 40,
        ///        &quot;Status&quot;: false,
        ///        &quot;Type&quot;: &quot;poison&quot;
        ///    },
        ///    &quot;3&quot;: {
        ///        &quot;Accuracy&quot;: -1,
        ///        &quot;DamageType&quot;: 0,
        ///        &quot;Name&quot;: &quot;Acid Armor&quot;,
        ///        &quot;Power&quot;: -1,
        ///        &quot;Status&quot;: true,
        ///        &quot;Type&quot;: &quot;poison&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string moves {
            get {
                return ResourceManager.GetString("moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    &quot;???&quot;,
        ///    &quot;Bulbasaur&quot;,
        ///    &quot;Ivysaur&quot;,
        ///    &quot;Venusaur&quot;,
        ///    &quot;Charmander&quot;,
        ///    &quot;Charmeleon&quot;,
        ///    &quot;Charizard&quot;,
        ///    &quot;Squirtle&quot;,
        ///    &quot;Wartortle&quot;,
        ///    &quot;Blastoise&quot;,
        ///    &quot;Caterpie&quot;,
        ///    &quot;Metapod&quot;,
        ///    &quot;Butterfree&quot;,
        ///    &quot;Weedle&quot;,
        ///    &quot;Kakuna&quot;,
        ///    &quot;Beedrill&quot;,
        ///    &quot;Pidgey&quot;,
        ///    &quot;Pidgeotto&quot;,
        ///    &quot;Pidgeot&quot;,
        ///    &quot;Rattata&quot;,
        ///    &quot;Raticate&quot;,
        ///    &quot;Spearow&quot;,
        ///    &quot;Fearow&quot;,
        ///    &quot;Ekans&quot;,
        ///    &quot;Arbok&quot;,
        ///    &quot;Pikachu&quot;,
        ///    &quot;Raichu&quot;,
        ///    &quot;Sandshrew&quot;,
        ///    &quot;Sandslash&quot;,
        ///    &quot;Nidoran F&quot;,
        ///    &quot;Nidorin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pokemon {
            get {
                return ResourceManager.GetString("pokemon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    [
        ///        11,
        ///        3
        ///    ],
        ///    [
        ///        11,
        ///        3
        ///    ],
        ///    [
        ///        11,
        ///        3
        ///    ],
        ///    [
        ///        9,
        ///        18
        ///    ],
        ///    [
        ///        9,
        ///        18
        ///    ],
        ///    [
        ///        9,
        ///        2
        ///    ],
        ///    [
        ///        10,
        ///        18
        ///    ],
        ///    [
        ///        10,
        ///        18
        ///    ],
        ///    [
        ///        10,
        ///        18
        ///    ],
        ///    [
        ///        6,
        ///        18
        ///    ],
        ///    [
        ///        6,
        ///        18
        ///    ],
        ///    [
        ///        6,
        ///        2
        ///    ],
        ///    [
        ///        6,
        ///        3
        ///    ],
        ///    [
        ///        6,
        ///        3
        ///    ],
        ///    [
        ///        6,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string pokemon_types {
            get {
                return ResourceManager.GetString("pokemon_types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018V.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
